# Generated by Django 5.0.7 on 2024-07-19 19:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0002_cardcontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardcontent",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created_at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cardcontent",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated_at"),
        ),
        migrations.AlterField(
            model_name="cardcontent",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="card_contents",
                to="pos.card",
            ),
        ),
    ]
