# Generated by Django 5.0.7 on 2024-07-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0003_cardcontent_created_at_cardcontent_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardcontent",
            name="expires_at",
            field=models.DateTimeField(null=True),
        ),
    ]
