# Generated by Django 5.0.7 on 2024-07-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0004_cardcontent_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardcontent",
            name="price",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
