version: '3.8'

services:
  web:
    build: ./app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  pgdata: