# Generated by Django 5.0.7 on 2024-07-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Contract Name"),
                ),
                ("price", models.IntegerField()),
                ("turnstile_timer", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
