# Generated by Django 5.0.7 on 2024-07-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0003_contract_validity_profile_validity_ticket_entries_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="contract",
            name="turnstile_timer",
            field=models.PositiveIntegerField(default=3600),
        ),
        migrations.AlterField(
            model_name="contract",
            name="validity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="profile",
            name="validity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="entries",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="validity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
