# Generated by Django 5.0.7 on 2024-07-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0006_prerequisite"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="must_have_all_prerequisites",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="must_have_all_prerequisites",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ticket",
            name="must_have_all_prerequisites",
            field=models.BooleanField(default=False),
        ),
    ]
