name: Build Docker image and run tests

on:
  push:
    branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Build docker container
            run: docker compose build web
          - name: Assert that the code is linted
            run: docker compose run --name lint-check web make check
          - name: Run Django Migrations
            run: docker compose run --name migrate web make migrate
          - name: Set up Python
            uses: actions/setup-python@v4
            with:
              python-version: '3.12.4'
          - name: Run tests and submit coverage to coveralls
            env:
              COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
            run: |
              pip install coveralls
              docker compose run web make test-coverage
              coveralls --submit=app/coverage.xml --srcdir=app