name: Build Docker image and run tests

on:
  push:
    branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Build docker container
            run: docker compose build web
          - name: Assert that the code is linted
            run: docker compose run web make check
          - name: Run Django Migrations
            run: docker compose run web make migrate
          - name: Launch tests with coverage
            env:
              COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
            run: docker compose run -e COVERALLS_REPO_TOKEN web make test-coverage